### ISSUE TITLE
Set background color for CountrySelectionDialog

### ISSUE THREAD

**Issue by jingwei99** [joelkanyi/KomposeCountryCodePicker#41]
Hey, I plan to use the library in my project and I'd like to be able to set the background color for `CountrySelectionDialog`. 

A proposal I have is to add a `countrySelectionDialogModifier` as a parameter to `KomposeCountryCodePicker`. 

Let me know. 

Thanks!

**Comment by joelkanyi** [comment]
Hey @jingwei99 thanks for raising this, I will add capabilities to change the container colour of the picker dialog today

**Comment by joelkanyi** [comment]
Hey @jingwei99 a new version of the library has been published: 1.1.0 

But there are some API changes:

First you need to define this state:
- ` val state = rememberKomposeCountryCodePickerState()`
- Then you can include it in the `KomposeCountryCodePicker` composable


Then as for accessing utility methods:
- Initially we were using `CountryCodePicker.getCountryPhoneCodeWithoutPrefix()` etc
- Now you need to access those methods using the `state` i.e `state.getCountryPhoneCodeWithoutPrefix()`


Then as for your request to add capabilities to change the background color of the picker dialog, we have two new parameters in `KomposeCountryCodePicker`:
- countrySelectionDialogContainerColor - Sets color of the country selection dialog container
- countrySelectionDialogContentColor - Sets color of the country selection dialog content

Kindly test it and let me know if anything does not work. You can also refer from the update `README.md`

Thanks

**Comment by jingwei99** [comment]
Yep, works perfectly, thanks Joel!

**Comment by joelkanyi** [comment]
Great 🎉
