### ISSUE TITLE
Cannot change color of county code

### ISSUE THREAD

**Issue by DisruptemJohnDominic** [joelkanyi/KomposeCountryCodePicker#42]
How to change country code color? I tried all the colors to make text color White

![image](https://github.com/joelkanyi/KomposeCountryCodePicker/assets/165661511/f9bbc7ee-db5b-47a0-a3e4-f052dc914aa6)

Result
![image](https://github.com/joelkanyi/KomposeCountryCodePicker/assets/165661511/4f3859fc-113a-40bb-bc04-5b1edd77b0cb)

**Comment by joelkanyi** [comment]
Hey @DisruptemJohnDominic thanks for reporting this issue, I have fixed it.

Please update to  v1.1.1

There is a new parameter called `pickerContentColor` in `KomposeCountryCodePicker` composable

Please confirm if it is okay

**Comment by joelkanyi** [comment]
Closing this as complete ✅
