### ISSUE TITLE
LocalSoftwareKeyboardController Crash 

### ISSUE THREAD

**Issue by Tonnie-Dev** [JoelKanyi/KomposeCountryCodePicker#7]
I am using Material 3 [Version 1.2.0-alpha07](https://developer.android.com/jetpack/androidx/releases/compose-material3#1.2.0-alpha07) and  [Compose UI Version 1.5.1](https://maven.google.com/web/index.html#androidx.compose.ui:ui) and I am getting this log crash while trying out KomposeCountryCodePicker.

> java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/ui/platform/LocalSoftwareKeyboardController;
>                  	at com.joelkanyi.jcomposecountrycodepicker.component.KomposeCountryCodePickerKt.KomposeCountryCodePicker(KomposeCountryCodePicker.kt:74)
> 
>  Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.compose.ui.platform.LocalSoftwareKeyboardController" on path: DexPathList[[dex file

There is a similar issue that I saw on this [unrelated bug report](https://github.com/stripe/stripe-android/issues/7184).

When I downgraded MD to `1.1.1` the code did not crash but crucial material three colors could not be resolved e.g. `MaterialTheme.colorScheme.surfaceContainerLowest`.

I also tried using **Integration with TextField** but the code still crashed.

Any leads on how to avert this crash will greatly be appreciated.

**Comment by JoelKanyi** [comment]
Let me look into the issues, then will get back to you

**Comment by JoelKanyi** [comment]
I have just created a sample, and all seems well: [sample usage](https://github.com/JoelKanyi/KomposePickerSample)
- Kotlin Version: 1.9.10
- Compose BOM Version: 2023.09.00 which translates to Compose Version 1.5.1
- Compose Compiler Version: 1.5.3
- KomposeCountryCodePicker Version: 1.0.3

**Comment by JoelKanyi** [comment]
Which stable version of material 3 is this offered? - `MaterialTheme.colorScheme.surfaceContainerLowest`

**Comment by Tonnie-Dev** [comment]
> Which stable version of material 3 is this offered? - `MaterialTheme.colorScheme.surfaceContainerLowest`

Only in

**Comment by Tonnie-Dev** [comment]
Thanks for the prompt review and the tips

After upgrading from Kotlin _1.9.0_ -> **_1.9.10_**, Compose Compiler _1.5.0_ -> **_1.5.3_** and Downgrading from _Material3:1.2.0-alpha07_ -> **_Material3:1.2.0-alpha03_**, KomposeCountryCodePicker is now working without crashing

`MaterialTheme.colorScheme.surfaceContainerLowest` is only available from on **`Material3:1.2.0-alpha03`** onwards. Let me play around with the your Library and I will report in case of any difficulties.

Thanks Man 👍🏽
