### ISSUE TITLE
KomposeCountryCodePicker usage with a Material TextField

### ISSUE THREAD

**Issue by Tonnie-Dev** [joelkanyi/KomposeCountryCodePicker#9]
I want to design my own TextField ( see below mock-up) and then Incorpolate KomposeCountryCodePicker

When I purely use the picker I am able to call all functions and all Texts below are being populated realtime out of box. However, when I use my own TextField and call the same functions the functions are not updating the texts.

![image](https://github.com/JoelKanyi/KomposeCountryCodePicker/assets/31527935/ea34984c-2c41-43a2-87d3-c5f2008d31f6)

Is there any way out to update the texts on typing when integrating with a custom TextField

![image](https://github.com/JoelKanyi/KomposeCountryCodePicker/assets/31527935/0ed86706-a153-4b0a-a060-8716576a0222)

**Comment by joelkanyi** [comment]
This has been fixed
